version: "3.8"
services:
  my-news:
    build: .
    container_name: vite_app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    env_file:
      - '.env.development.local'
      - '.env'
