version: "3.8"
services:
  my-news:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-news-development
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/my-news/src
#    stdin_open: true
#    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
